apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: dhcp
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: dhcp
      spec:
        containers:
        - name: dhcp
          image: npflan/serverteam-dhcp:latest
          volumeMounts:
            - mountPath: /var/lib/dhcp
              name: iscsipd-dhcp-1
          resources:
            limits:
              memory: 100M

        volumes:
          - name: iscsipd-dhcp-1
            iscsi:
              targetPortal: 10.100.201.220:3260
              portals: ['10.100.201.220:3260', '10.100.201.230:3260', '10.100.202.220:3260', '10.100.202.230:3260']
              iqn: iqn.1986-03.com.hp:storage.p2000g3.1022db2a48
              lun: 0
              fsType: ext4
              readOnly: false
        initContainers:
          - name: install
            image: busybox
            command:
              - touch
              - "/var/lib/dhcp/dhcpd.leases"
            volumeMounts:
            - mountPath: /var/lib/dhcp
              name: iscsipd-dhcp-1
- kind: Service
  apiVersion: v1
  metadata:
    name: dhcp
  spec:
    clusterIP: 10.100.128.2
    selector:
      app: dhcp
    ports:
      - name: dhcp
        protocol: UDP
        port: 67
        targetPort: 67
