apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: serverteam-dhcp
    name: serverteam-dhcp
    namespace: default
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: serverteam-dhcp
      spec:
        containers:
        - image: docker.io/npflan/serverteam-dhcp:latest
          imagePullPolicy: Always
          name: serverteam-dhcp
          volumeMounts:
              - mountPath: /var/lib/dhcp
                name: iscsipd-dhcp-1
          resources:
            limits:
              memory: 100M
          
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File

        volumes:
          - name: iscsipd-dhcp-1
            persistentVolumeClaim:
              claimName: serverteam-dhcp-pv-claim
        initContainers:
           - name: install
             image: busybox
             command:
              - touch
              - "/var/lib/dhcp/dhcpd.leases"
             volumeMounts:
             - mountPath: /var/lib/dhcp
               name: iscsipd-dhcp-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
- kind: Service
  apiVersion: v1
  metadata:
    labels:
      app: serverteam-dhcp
    name: serverteam-dhcp
    namespace: default
  spec:
    clusterIP: 10.101.128.127
    ports:
    - name: dhcp-udp
      port: 67
      protocol: UDP
      targetPort: 67
    selector:
      app: serverteam-dhcp
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}

- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: serverteam-dhcp-pv-claim
  spec:
    storageClassName: manual
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
