apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: serverteam-dhcp
  name: serverteam-dhcp
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: serverteam-dhcp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: serverteam-dhcp
    spec:
      containers:
      - image: docker.io/npflan/serverteam-dhcp:latest
        imagePullPolicy: Always
        name: serverteam-dhcp
        ports:
        - containerPort: 67
          protocol: TCP
        - containerPort: 67
          protocol: UDP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: serverteam-dhcp
  name: serverteam-dhcp
  namespace: default
spec:
  clusterIP: 10.101.128.127
  ports:
  - name: dhcp-udp
    port: 67
    protocol: UDP
    targetPort: 67
  selector:
    run: serverteam-dhcp
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}